name: PushFile

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Build and deploy
      #   # env:
      #   #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
      #     # DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
      
      - name: Create File
        run: |
          echo "Test file 22:50pm" >> test2315.txt

      - name: Commit Files
        run: |
          git config --global user.name "ptn111"
          git config --global user.email "32492807+ptn111@users.noreply.github.com"

          git checkout -b notebook
          git pull origin notebook
          git add -A
          git commit -a -m "Update test2315.txt"
          git push --set-upstream origin notebook