name: PushFile

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        
      - name: Check out repository 
        run: 
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub Actions."
          
          echo "The name of current branch is ${{ github.ref }} and its repository is ${{ github.repository }}."
      
      # - name: Build and deploy
      #   # env:
      #   #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
      #     # DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
      


      - name: Display the path
        shell: bash
        run: |
          echo "Here is the path of current folder"
          echo $PATH


      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'

      - name: Execute Julia Command
        shell: bash
        run: |
          echo ".................."
          echo "Here is in the pwd"
          ls
          cd docs
          echo ".................."
          echo "Here is in the docs folder"
          ls
          julia gen_notebook.jl
          julia -e 'gen_notebook.jl'
        

