name: PushFile

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository 
        uses: actions/checkout@v2
        run: 
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub Actions."
          
          echo "The name of current branch is ${{ github.ref }} and its repository is ${{ github.repository }}."
      
      # - name: Build and deploy
      #   # env:
      #   #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
      #     # DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
      
      - name: Create File
        run: |
          echo "Test file 23:55pm" >> test2355.txt


      - name: Display the path
        shell: bash
        run: |
          echo "Here is the path of current folder"
          echo $PATH


        

      # - name: Commit Files
      #   run: |
      #     git config --global user.name "ptn111"
      #     git config --global user.email "32492807+ptn111@users.noreply.github.com"

      #     git add -A
      #     git commit -a -m "Update test.txt"
      #     git branch notebook
      #     git push --force origin master:notebook

   